var objJson = [
    { prayerName: "Ακολουθία του Εσπερινού", linkName: "akolouthia_tou_esperinou"},
    { prayerName: "Μακαρισμοί του Κυρίου", linkName: "makarismoi_tou_kiriou"},
    { prayerName: "Προσευχή κατά την χαραυγή", linkName: "proseuxi_kata_tin_xaraugi"},
    { prayerName: "Ακολουθία του Μεσονυκτικού", linkName: "akolouthia_tou_mesonyktikou"},
    { prayerName: "Μικρά Παράκλησις", linkName: "mikra_paraklisis"},
    { prayerName: "Παρακλητικός Κανών Οσίου Ιωάννου του Ρώσου", linkName: "paraklitikos_kanon_osiou_ioannou_tou_rosou"},
    { prayerName: "Τροπάριο Κασσιανής (ἡ ἐν πολλαῖς ἁμαρτίαις…)", linkName: "tropario_kassianis_i_en_pollais_amartiais"},
    { prayerName: "Το Σύμβολο της Πίστεως", linkName: "to_simvolo_tis_pistews"},
    { prayerName: "Ευχή της Τραπέζης (Γεύμα)", linkName: "euxi_tis_trapezis_geuma"},
    { prayerName: "Σ’ ευχαριστώ (Αγίου Συμεών του Νέου Θεολόγου)", linkName: "sexuxaristw_agiou_simewn_tou_neou_theologou"},
    { prayerName: "Η προσευχή της Αγάπης", linkName: "i_proseuxi_tis_agapis"},
    { prayerName: "Σύντομη πρωινή και βραδυνή προσευχή", linkName: "sintomi_proini_kai_vradini_proseuxi"},
    { prayerName: "Ο Ακάθιστος Ύμνος", linkName: "o_akathistos_imnos"},
    { prayerName: "Καταβασίες των Χριστουγέννων", linkName: "katavasies_twn_xristougennwn"},
    { prayerName: "Αναστάσιμη Προσευχή", linkName: "anastasimi_proseuxi"},
    { prayerName: "Αιτήματα Θείας Ευχαριστίας", linkName: "aitimata_theias_euxaristias"},
    { prayerName: "Κανόνας της Θείας Μεταλήψεως", linkName: "kanonas_tis_theias_metalipseos"},
    { prayerName: "Προσευχή νοσηλευτού και νοσηλεύτριας", linkName: "proseuxi_nosileutou_kai_nosileutrias"},
    { prayerName: "Μια Προσευχή για τους Kεκοιμημένους", linkName: "mia_proseuxi_gia_tous_kekoimimenous"},
    { prayerName: "Προσευχή θερμή γέροντος Πορφυρίου", linkName: "proseuxi_thermi_gerontos_porfiriou"},
    { prayerName: "Προσευχή Μετάνοιας και Απολύτρωσης", linkName: "proseuxi_metanoias_kai_apolitrosis"},
    { prayerName: "Θεοτόκε Παρθένε", linkName: "theotoke_parthene"},
    { prayerName: "Παναγία Τριάς, ελέησον ἡμάς", linkName: "panagia_trias_eleison_imas"},
    { prayerName: "Μη καταπιστεύσης με", linkName: "mi_katapisteuseis_me"},
    { prayerName: "Τη Θεοτόκω εκτενώς νυν προσδράμωμεν", linkName: "ti_theotoko_ektenos_nin_prosdramomen"},
    { prayerName: "Ωδή πρός την Υπεραγία Θεοτόκο (Αγίου Νεκταρίου)", linkName: "odi_pros_tin_iperageia_theotoko_agiou_nektariou"},
    { prayerName: "Ο μονογενής Υιός και Λόγος του Θεού", linkName: "o_monogenis_ios_kai_logos_tou_theou"},
    { prayerName: "Ευχή Αγίου Εφραίμ του Σύρου", linkName: "euxi_agiou_efraim_tou_syrou"},
    { prayerName: "Ευχή Γ. Σωφρονίου του Essex", linkName: "euxi_sofroniou_tou_essex"},
    { prayerName: "Ἡ Προσευχή τοῦ Ἀγίου Ἀνδρέου τοῦ Σαλοῦ", linkName: "i_proseuxi_tou_agiou_andrea_tou_salou"},
    { prayerName: "Προσευχή ευγνωμοσύνης (Αγίου Σιλουανού του Αθωνίτου)", linkName: "proseuxi_eugnomosinis_agiou_silouanou_tou_athonitou"},
    { prayerName: "Ευχή μπροστά στον Πανάγιο Τάφο", linkName: "euxi_mprosta_ston_panagio_tafo"},
    { prayerName: "Δόξα Πατρὶ καὶ Υἱῷ καὶ Ἁγίῳ Πνεύματι", linkName: "doxa_patri_kai_io_kai_agiw_pneumati"},
    { prayerName: "Πρωινή Ευχή (Γ. Σωφρονίου)", linkName: "proini_euxi_sofroniou"},
    { prayerName: "Ευχὴ προς τον Άγιον Τιμόθεον Επίσκοπον Ευρίπου", linkName: "euxi_pros_ton_agio_timotheo_episkopo_euripou"},
    { prayerName: "Τις θεός μέγας", linkName: "tis_theos_megas"},
    { prayerName: "Δεύτε προσκυνήσωμεν", linkName: "deute_proskinisomen"},
    { prayerName: "Ευχή ἀναγινωσκώμενη εἰς πᾶσαν ἀσθένειαν και γοητείαν και μαγείαν", linkName: "euxi_anaginoskomeni_eis_pasan_astheneian_kai_goiteian_kai_mageian"},
    { prayerName: "Η προσευχή του Κυρίου στα Αραμαϊκά", linkName: "i_proseuxi_tou_kiriou_sta_aramaika"},
    { prayerName: "Προσευχή Πολεμικής Αεροπορίας", linkName: "proseuxi_polemikis_aeroporias"},
    { prayerName: "Επi Σoί Χαίρει, Κεχαριτωμένη", linkName: "epi_soi_keharitomeni"},
    { prayerName: "Ευχή του Αγίου Ιωαννικίου", linkName: "euxi_tou_agiou_ioannikiou"},
    { prayerName: "Ωδή Συμεών του θεοδόχου (Νυν απολύεις)", linkName: "odi_simeon_tou_theodohou_nin_apolyeis"},
    { prayerName: "Ευχή ἐτέρα ἀναγινωσκώμενη τῆ 7η Φεβρουαρίου επί τη μνήμη του Αγ.Παρθενιου", linkName: "euxi_etera_anaginoskomeni_ti_evdomi_fevrouariou_epi_ti_mnimi_tou_agiou_partheniou"},
    { prayerName: "Προστασία των Χριστιανών", linkName: "prostasia_twn_xristianwn"},
    { prayerName: "Ψαλμός ρβ´ (102ος) - Ευλόγει η ψυχή μου, τον Κύριον", linkName: "psalmos_102_eulogei_i_psixi_mou_ton_kirion"},
    { prayerName: "Τρισάγιο (Άγιος ο Θεός)", linkName: "trisagio_agios_o_theos"},
    { prayerName: "Τας κεφαλάς ημών τω Κυρίω κλίνωμεν", linkName: "tas_kefalas_imwn_tw_kiriw_klinomen"},
    { prayerName: "Ψαλμός ρλε´ (135ος) - Εξομολογείσθε τω Κυρίω", linkName: "psalmos_135_eksomologisthe_tw_kiriw"},
    { prayerName: "Επιλύχνιος Ευχαριστία (Φως ιλαρόν)", linkName: "epilixnios_euxaristia_fos_ilaron"},
    { prayerName: "Ψαλμός ρμβ´ (142ος) - Κύριε εισάκουσον της προσευχής μου", linkName: "psalmos_142_kirie_eisakouson_tis_proseuxis_mou"},
    { prayerName: "Μεγάλη Εβδομάδα", linkName: "megali_evdomada"},
    { prayerName: "Καρδιακή προσευχή ΚΙΧΕΜ", linkName: "kardiaki_proseuxi_kixem"},
    { prayerName: "Ύμνος των Αγίων τριών παίδων (Τον Κύριον υμνείτε)", linkName: "ymnos_twn_agiwn_triwn_paidwn_ton_kirio_imneite"},
    { prayerName: "Κανών της Θεοτόκου", linkName: "kanon_tis_theotokou"},
    { prayerName: "Ψαλμός κβ´ (22ος) - Κύριος ποιμαίνει με", linkName: "psalmos_22_kyrios_poimainei_me"},
    { prayerName: "Προσευχή στην Υπεραγία Θεοτόκο (Αγ Νικοδήμου Αγιορείτου)", linkName: "proseuxi_stin_iperageia_theotoko_agiou_nikodimou_agioreitou"},
    { prayerName: "Ψαλμός ξθ´ (69ος) - Ο Θεός εις την βοήθειάν μου πρόσχες", linkName: "psalmos_69_o_theos_eis_tin_voitheian_mou_proshes"},
    { prayerName: "Ψαλμός ν´ (50ος) - Ελέησον με ο Θεός", linkName: "psalmos_50_eleison_me_o_theos"},
    { prayerName: "Κύριε εκέκραξα προς Σε", linkName: "kirie_ekekraksa_pros_se"},
    { prayerName: "Ψαλμός Αποδείπνου - Κύριε των Δυνάμεων", linkName: "psalmos_apodeipnou_kirie_twn_dinamewn"},
    { prayerName: "Ψαλμός Εσπερινού - Θου Κύριε φυλακήν τω στόματί μου", linkName: "psalmos_esperinou_thou_kirie_filakin_to_stomati_mou"},
    { prayerName: "Άξιον εστίν (Μεγαλυνάρια της Παναγίας)", linkName: "aksion_estin_megalinaria_tis_panagias"},
    { prayerName: "Κύριε ελέησον", linkName: "kirie_eleison"},
    { prayerName: "Προσευχή εις την Θεοτόκο", linkName: "proseuxi_eis_tin_theotoko"},
    { prayerName: "Προσευχή των δακρύων (Όσιος Ισαάκ ο Σύρος)", linkName: "proseuxi_twn_dakriwn_osios_isaak_o_siros"},
    { prayerName: "Προσευχή των γονέων για τα παιδιά τους", linkName: "proseuxi_twn_gonewn_gia_ta_paidia"},
    { prayerName: "Προσευχή της οικογένειας (Γ. Σωφρονίου)", linkName: "proseuxi_tis_oikogeneias_sofroniou"},
    { prayerName: "Ο Ύμνος της Αγάπης", linkName: "o_imnos_tis_agapis"},
    { prayerName: "Ευχή των Ωρών (Ὁ ἐν παντὶ καιρῷ…)", linkName: "euxi_twn_orwn_o_en_panti_kairw"},
    { prayerName: "Απόδειπνος λόγος (Καὶ δὸς ἡμῖν, Δέσποτα)", linkName: "apodeipnos_logos_kai_dos_imin_despota"},
    { prayerName: "Ευχή Μυστική του Αγ. Συμεών", linkName: "euxi_mistiki_tou_agiou_symewn"},
    { prayerName: "Ευχή της Θείας Μεταλήψεως", linkName: "euxi_tis_theias_metalipsews"},
    { prayerName: "Ο εξάψαλμος", linkName: "o_eksapsalmos"},
    { prayerName: "Μέγας Κανών (Αγ.Ανδρέα Κρήτης)", linkName: "megas_kanwn_agiou_andrea_kritis"},
    { prayerName: "Χαιρετισμοί εις τον Κύριο Ιησού Χριστό", linkName: "hairetismoi_eis_ton_kirio_iisou_xristo"},
    { prayerName: "Χαιρετισμοί της Αγίας Άννας", linkName: "hairetismoi_tis_agias_annas"},
    { prayerName: "Μεγάλο Απόδειπνο", linkName: "megalo_apodeipno"},
    { prayerName: "Χαιρετισμοί εις τους Αρχαγγέλους", linkName: "hairetismoi_eis_tous_arxaggelous"},
    { prayerName: "Άσπιλε, αμόλυντε", linkName: "aspile_amolinte"},
    { prayerName: "Πάτερ ημών (Κυριακή προσευχή)", linkName: "pater_imwn_kyriaki_proseuxi"},
    { prayerName: "Προσευχή στον Άγιο Αρχάγγελο Μιχαήλ", linkName: "proseuxi_ston_agio_arxaggelo_michail"},
    { prayerName: "Ευχή προς τον Φύλακα Άγγελο", linkName: "euxi_pros_ton_fylaka_aggelo"},
    { prayerName: "Δόξα ἐν ὑψίστοις Θεῷ", linkName: "doksa_en_ipsistois_thew"},
    { prayerName: "Βασιλεύ Ουράνιε", linkName: "valiseu_ouranie"},
    { prayerName: "Ψαλμός λγ´ (33ος) - Ευλογήσω Τον Κύριον", linkName: "psalmos_33_eulogisw_ton_kirion"},
    { prayerName: "Χερουβικός Ύμνος", linkName: "herouvikos_imnos"},
    { prayerName: "Ευχή εις απειλήν λοιμικής ασθένειας", linkName: "euxi_eis_apeilin_loimikis_astheneias"},
    { prayerName: "Προοιμιακή προσευχή", linkName: "prooimiaki_proseuxi"},
    { prayerName: "Χαιρετισμοί της Υπεραγίας Θεοτόκου", linkName: "hairetismoi_tis_iperagias_theotokou"},
    { prayerName: "Αγνή Παρθένε Δέσποινα (Αγίου Νεκταρίου)", linkName: "agni_parthene_despoina"},
    { prayerName: "Προσευχή για την κατάπαυση του πολέμου στην Ουκρανία", linkName: "proseuxi_gia_tin_katapausi_tou_polemou_stin_oukrania"},
    { prayerName: "Ευχή των Πατέρων της Όπτινα", linkName: "euhi_twn_paterwn_tis_optina"},
    { prayerName: "Ευχαριστία μετά την Θεία Μετάληψη", linkName: "euxaristia_meta_ti_theia_metalipsi"},
    { prayerName: "Παρακλητικός Κανόνας εις τους Αρχαγγέλους", linkName: "paraklitikos_kanonas_eis_tous_arhaggelous"},
    { prayerName: "Μέγας Παρακλητικός Κανόνας", linkName: "megas_paraklitikos_kanonas"},
    { prayerName: "Ικετήριος κανόνας εις τον Ιησού Χριστό", linkName: "iketirios_kanonas_eis_ton_iisou_xristo"},
    { prayerName: "Επιμνημόσυνη δέηση", linkName: "epimnimosini_deisi"},
    { prayerName: "Ακολουθία εις ψυχορραγούντα", linkName: "akolouthia_eis_psihoraggounta"},
    { prayerName: "Επίκληση της Σοφίας (Βασιλέως Σολομώντα)", linkName: "epiklisi_tis_sofias_vasilews_solomwnta"},
    { prayerName: "Άγιος, Άγιος, Άγιος Κύριος Σαβαώθ", linkName: "agios_agios_agios_kirios_savawth"},
    { prayerName: "Ευχὴ πριν/μετὰ την Ιερὰ Εξομολόγηση", linkName: "euhi_prin_meta_tin_iera_eksomologisi"},
    { prayerName: "Ευχή κατά την παρασκευή του προσφόρου", linkName: "euhi_kata_tin_paraskevi_tou_prosforou"},
    { prayerName: "Ευχή κατά την παρασκευή της Φανουρόπιτας", linkName: "euhi_kata_tin_paraskevi_tis_fanouropitas"},
    { prayerName: "Συγχωρετική ευχή", linkName: "sigxwretiki_euhi"},
    { prayerName: "Μικρό Απόδειπνο", linkName: "mikro_apodeipno"},
    { prayerName: "Μνήσθητι Κύριε! (Οσίου Παϊσίου)", linkName: "mnisthiti_kirie_osiou_paisiou"},
    { prayerName: "Προσευχή για την αϋπνία", linkName: "proseuxi_gia_tin_aipnia"},
    { prayerName: "Ευχή για απαλλαγή από τους αισχρούς λογισμούς", linkName: "euhi_gia_apallagi_apo_tous_aisxrous_logismous"},
    { prayerName: "Ευχὴ Ἁγιογράφου", linkName: "euhi_agiografou"},
    { prayerName: "Τα καθ΄ημέρα απολυτίκια", linkName: "ta_kathimera_apolitikia"},
    { prayerName: "Ευχή επί βασκανία", linkName: "euhi_epi_vaskania"},
    { prayerName: "Ευχὴ Αντιφώνου Α´", linkName: "euhi_antifonou_a"},
    { prayerName: "Ευχὴ Αντιφώνου Β´", linkName: "euhi_antifonou_b"},
    { prayerName: "Αναστάσιμα Απολυτίκια στους 8 ήχους", linkName: "anastasima_apolitikia_stous_8_ihous"},
    { prayerName: "Ἑσπερινὴ Εὐχὴ Δευτέρας", linkName: "esperini_euhi_deuteras"},
    { prayerName: "Ἑσπερινὴ Εὐχὴ Κυριακῆς", linkName: "esperini_euhi_kiriakis"},
    { prayerName: "Ἑσπερινὴ Εὐχὴ Παρασκευῆς", linkName: "esperini_euhi_paraskevis"},
    { prayerName: "Ἑσπερινὴ Εὐχὴ Πέμπτης", linkName: "esperini_euhi_pemptis"},
    { prayerName: "Ἑσπερινὴ Εὐχὴ Σαββάτου", linkName: "esperini_euhi_savvatou"},
    { prayerName: "Ἑσπερινὴ Εὐχὴ Τετάρτης", linkName: "esperini_euhi_tetartis"},
    { prayerName: "Ἑσπερινὴ Εὐχὴ Τρίτης", linkName: "esperini_euhi_tritis"},
    { prayerName: "Ευχή Α΄ γονυκλισίας Πεντηκοστής", linkName: "euhi_a_goniklisias_pentikostis"},
    { prayerName: "Ευχή Β΄ γονυκλισίας Πεντηκοστής", linkName: "euhi_b_goniklisias_pentikostis"},
    { prayerName: "Ευχή Γ΄ γονυκλισίας Πεντηκοστής", linkName: "euhi_c_goniklisias_pentikostis"},
    { prayerName: "Ευχή για απαλλαγή από τον θυμό", linkName: "euhi_gia_apallagi_apo_ton_thimo"},
    { prayerName: "Ευχή εις ασθενούντα", linkName: "euhi_eis_asthenounta"},
    { prayerName: "Ευχή Γ'", linkName: "euhi_c"},
    { prayerName: "Ευχή εξομολογητική εις τον Κύριον", linkName: "euhi_eksomologitiki_eis_ton_kirion"},
    { prayerName: "Ευχή πριν/μετά το γεύμα", linkName: "euhi_prin_meta_geuma"},
    { prayerName: "Ευχή πριν/μετά το δείπνο", linkName: "euhi_prin_meta_deipno"},
    { prayerName: "Προσευχή για τον Καρκίνο", linkName: "proseuxi_gia_ton_karkino"},
    { prayerName: "Προσευχή για σωματική και ψυχική υγεία", linkName: "proseuxi_gia_somatiki_kai_psihiki_igeia.html"},
    { prayerName: "Προσευχή για πονοκέφαλο, το ρίγος ή τον πυρετό και γενικά τον πόνο", linkName: "proseuxi_gia_ponokefalo_rigos_pireto_pono.html"}
];
 

window.onload = function() {
  a = document.getElementById('link');
  var randomLink = Math.floor(Math.random() * objJson.length);
  a.setAttribute("href", objJson[randomLink].linkName + ".html");
}